jobs:
- job: Region_1
  displayName: Performance Agent Instance 1
  pool:
    vmImage: vs2017-win2016
  variables:
  - group: PerformanceVariableGroup
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Update JMX File Parameters
    inputs:
      targetType: inline
      script: "# Change jmeter parameters\n\nsed -i 's/RESOURCE_ID/$(PerfTestResourceId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_ID/$(PerfTestClientId)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/CLIENT_SECRET/$(PerfTestClientSecret)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/RAMP_TIME/$(RAMP_TIME)/g' $(JmeterFolderPath)/$(JmeterFileName)\n \nsed -i 's/DURATION/$(DURATION)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/LOOPS/$(LOOPS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n\nsed -i 's/THREADS/$(THREADS)/g' $(JmeterFolderPath)/$(JmeterFileName)\n"
  - task: PowerShell@2
    displayName: Run Performance in Region1
    inputs:
      targetType: filePath
      filePath: ./JMeterAKSPipeline/ExecuteInAKS.ps1
      arguments: '-AKSClusterName $(AKSClusterNameRegion1) -ResourceGroup $(AKSResourceGroupRegion1) -SPNClientId $(AKSSPNClientIdRegion1) -SPNClientSecret $(AKSSPNClientSecretRegion1) -TenantId $(TenantId) -Namespace $(Namespace) -JMeterFolderPath $(JmeterFolderPath) -JMeterFileName $(JmeterFileName) -CSVFileNames "$(CSVFileNames)"'
      pwsh: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    continueOnError: True
    inputs:
      path: $(JmeterFolderPath)/$(AKSClusterNameRegion1)
      artifactName: Results-Region1-$(THREADS)-$(DURATION)
...
